name: ts-goap
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: test and build
    steps:
      - uses: actions/checkout@v4

      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: true

      - name: test
        run: npm run test